In [1]:
import numpy as np

1. 类型转换


In [4]:
array01=np.linspace(1,20,10)
array01


array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [8]:
array01_int=array01.astype(np.int64)
array01_float=array01_int.astype(np.float64)
array01_str=array01_float.astype(np.string_)
array01_str

array([b'1.0', b'3.0', b'5.0', b'7.0', b'9.0', b'11.0', b'13.0', b'15.0',
       b'17.0', b'20.0'], dtype='|S32')

2. 运算

narray 运算为广播运算,**numpy中自带循环**

In [9]:
array02=np.arange(12).reshape(3,-1)

In [18]:
array02+1
array02*3
1/array02
array02**2


<ipython-input-18-d0db18bf8df4>:3: RuntimeWarning: divide by zero encountered in true_divide
  1/array02


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [15]:
# 两个数组运算要ndim 相同，对应位置相加

array03=np.full((3,4),10)
array03

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [19]:
array02+array03
array02/array03
array02>array03

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

3. 数组合并与拆分

In [31]:
array04=np.arange(9).reshape(3,-1)
array05=np.arange(10,19).reshape(3,-1)

In [33]:
np.vstack((array04,array05))  #vertical
np.hstack((array04,array05))  #horizontal

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

In [34]:
array06= np.arange(32).reshape(8,-1)
array06

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

拆分数组

In [35]:
fir,sec,thd=np.split(array06,[2,4])
fir

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [36]:
sec

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 4. 数组切片

In [51]:
array07=np.arange(10,20)
array07[:2]
array07[2:]
array07[1:4]
array07[:]
array07[1:7:2]
array07[-1:2:-1]
array07[::-1]
array07[[1,4,0]]

array([11, 14, 10])

二维数组

In [46]:
array08=np.arange(12).reshape(3,4)

In [60]:
array08[2,2]
array08[:2]
array08[:2,:2]
array08[:2,[0,2]]
array08[:,[0,2]][[0,2],:]

array([[ 0,  2],
       [ 8, 10]])


       [[ 0,  1,  2,  3,  4],

       [ 5,  6,  7,  8,  9],
       
       [10, 11, 12, 13, 14],
       
       [15, 16, 17, 18, 19],
       
       [20, 21, 22, 23, 24]]
       
我们想要这样的矩阵

        [
            [6,9],
            [11,14]
        ]

#### 5. 数据筛选

In [61]:
array08[array08%2==0]

array([ 0,  2,  4,  6,  8, 10])

In [64]:
array08[[True,True,False]]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])